version: '3.8'

services:
  api:
    build: .
    container_name: node-app
    restart: unless-stopped
    command: npm start -L
    env_file: .env
    ports:
      - '3000:3000'
    networks:
      - app-network

networks:
  app-network:
    external: true
